# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Travis Askham'
tagline:          ''
description:      'Research Associate'
department:       '<a href="https://amath.washington.edu/">Applied Math</a>'
school: 	  '<a href="https://washington.edu">University of Washington</a>'
url:              'https://askhamwhat.github.io'
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Travis Askham'
  url:            

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.7.1
sidebar_home_link:  true
sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  profile: 'https://github.com/askhamwhat'

googlescholarpage: 'https://scholar.google.com/citations?user=YROcY-QAAAAJ&hl=en'

collections:
  news:
    output: false
  upcoming:
    output: false
  publications:
    output: true
    permalink: /:collection/:name
